apiVersion: v1
kind: Secret
metadata:
  name: git-secret
  annotations:
    tekton.dev/git-0: <your-github-repo ie. https://github.ibm.com/DevOps-Trainings/health-ui>
type: kubernetes.io/basic-auth
stringData:
  username: <your-w3-id>
  password: <your-github-token>
